// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7PbkEvZ_mLFb-shNF3ihwG5dXwd7ZhF0',
    appId: '1:256184294492:web:e0301ffc5c9b031c985a99',
    messagingSenderId: '256184294492',
    projectId: 'flutter-firebase-90a66',
    authDomain: 'flutter-firebase-90a66.firebaseapp.com',
    storageBucket: 'flutter-firebase-90a66.appspot.com',
    measurementId: 'G-P5GNL0556F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGTOFQnkukhy8jGYgX-w5P2uaYa4mgm8E',
    appId: '1:256184294492:android:d82147259e27523a985a99',
    messagingSenderId: '256184294492',
    projectId: 'flutter-firebase-90a66',
    storageBucket: 'flutter-firebase-90a66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWOljavsqm4spCAOoaD5EMxp9DDRqAoiI',
    appId: '1:256184294492:ios:28f773e3a3b9723d985a99',
    messagingSenderId: '256184294492',
    projectId: 'flutter-firebase-90a66',
    storageBucket: 'flutter-firebase-90a66.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

}